// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1tTG8U6ohSGtravRLZOWqqm5kWcnlqc',
    appId: '1:650591086297:web:f121c925c8cc9703bb00c8',
    messagingSenderId: '650591086297',
    projectId: 'chart-mentor',
    authDomain: 'chart-mentor.firebaseapp.com',
    storageBucket: 'chart-mentor.firebasestorage.app',
    measurementId: 'G-BJ9D4H19W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuCCNyNHpWTIhd_dAJ8oLFjjur-pedeJU',
    appId: '1:650591086297:android:94ebfec0fcef0f91bb00c8',
    messagingSenderId: '650591086297',
    projectId: 'chart-mentor',
    storageBucket: 'chart-mentor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD00mdsWZKdpaZ8l-aN9m2qsSkf3qGeHAo',
    appId: '1:650591086297:ios:b163b4b53849dafbbb00c8',
    messagingSenderId: '650591086297',
    projectId: 'chart-mentor',
    storageBucket: 'chart-mentor.firebasestorage.app',
    iosBundleId: 'com.chart.mentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD00mdsWZKdpaZ8l-aN9m2qsSkf3qGeHAo',
    appId: '1:650591086297:ios:19507be861c37d9fbb00c8',
    messagingSenderId: '650591086297',
    projectId: 'chart-mentor',
    storageBucket: 'chart-mentor.firebasestorage.app',
    iosBundleId: 'com.example.chatMentor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq1tTG8U6ohSGtravRLZOWqqm5kWcnlqc',
    appId: '1:650591086297:web:f6e942a48977de04bb00c8',
    messagingSenderId: '650591086297',
    projectId: 'chart-mentor',
    authDomain: 'chart-mentor.firebaseapp.com',
    storageBucket: 'chart-mentor.firebasestorage.app',
    measurementId: 'G-92BEP59NPY',
  );
}
